# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [2]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [3]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [4]:
np.arange(2,200)

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 18

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [5]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [7]:
b= a[:4, :]
print(b)

[[0.84062117 0.48006452 0.7876326  0.77109654]
 [0.44409793 0.09014516 0.81835917 0.87645456]
 [0.7066597  0.09610873 0.41247947 0.57433389]
 [0.29960807 0.42315023 0.34452557 0.4751035 ]]


### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [57]:
if a.any() >= 0.5:
    b= a[:10, :]
print(b)

[[0.84062117 0.48006452 0.7876326  0.77109654]
 [0.44409793 0.09014516 0.81835917 0.87645456]
 [0.7066597  0.09610873 0.41247947 0.57433389]
 [0.29960807 0.42315023 0.34452557 0.4751035 ]
 [0.17003563 0.46843998 0.92796258 0.69814654]
 [0.41290051 0.19561071 0.16284783 0.97016248]
 [0.71725408 0.87702738 0.31244595 0.76615487]
 [0.20754036 0.57871812 0.07214068 0.40356048]
 [0.12149553 0.53222417 0.9976855  0.12536346]
 [0.80930099 0.50962849 0.94555126 0.33364763]]


### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [61]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [63]:
b[4,1,2]
print(b)

[[[0.55867166 0.06210792 0.08147297]
  [0.82579068 0.91512478 0.06833034]]

 [[0.05440634 0.65857693 0.30296619]
  [0.06769833 0.96031863 0.51293743]]

 [[0.09143215 0.71893382 0.45850679]
  [0.58256464 0.59005654 0.56266457]]

 [[0.71600294 0.87392666 0.11434044]
  [0.8694668  0.65669313 0.10708681]]

 [[0.07529684 0.46470767 0.47984544]
  [0.65368638 0.14901286 0.23760688]]]


### 6. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [72]:
if b.any() <= 0.5:
    x = a[:10]
print(a)

[[0.84062117 0.48006452 0.7876326  0.77109654]
 [0.44409793 0.09014516 0.81835917 0.87645456]
 [0.7066597  0.09610873 0.41247947 0.57433389]
 [0.29960807 0.42315023 0.34452557 0.4751035 ]
 [0.17003563 0.46843998 0.92796258 0.69814654]
 [0.41290051 0.19561071 0.16284783 0.97016248]
 [0.71725408 0.87702738 0.31244595 0.76615487]
 [0.20754036 0.57871812 0.07214068 0.40356048]
 [0.12149553 0.53222417 0.9976855  0.12536346]
 [0.80930099 0.50962849 0.94555126 0.33364763]]


### 7. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [27]:
import os
import glob

path = r"C:\Users\benja\IronHack\ironhack-firstweek\tutorial_lab\lab-list-comprehensions\data"
extension = 'csv'
os.chdir(path)
result = glob.glob('*.{}'.format(extension))
filenames = print(result)

['sample_file_0.csv', 'sample_file_1.csv', 'sample_file_2.csv', 'sample_file_3.csv', 'sample_file_4.csv', 'sample_file_5.csv', 'sample_file_6.csv', 'sample_file_7.csv', 'sample_file_8.csv', 'sample_file_9.csv']


### 8. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [79]:
dfs = pd.concat([pd.read_csv("" + f) for f in result])
print(dfs.head(9))

          0         1         2         3         4         5         6  \
0  0.734751  0.195362  0.734309  0.598184  0.763433  0.263434  0.868066   
1  0.772607  0.445391  0.249642  0.787922  0.598583  0.827238  0.624126   
2  0.226428  0.268764  0.694262  0.622335  0.063843  0.122683  0.815625   
3  0.362748  0.495430  0.113876  0.594149  0.612522  0.625204  0.864050   
4  0.033415  0.340433  0.464971  0.363737  0.025815  0.434129  0.415163   
0  0.276827  0.260054  0.942397  0.113187  0.781355  0.475740  0.152061   
1  0.995885  0.158381  0.244274  0.962163  0.651900  0.930665  0.577190   
2  0.641917  0.821055  0.392437  0.782617  0.510762  0.428320  0.017324   
3  0.806532  0.569258  0.148175  0.809987  0.459632  0.735762  0.730664   

          7         8         9        10        11        12        13  \
0  0.058092  0.753502  0.587513  0.311608  0.178356  0.182922  0.147631   
1  0.601524  0.688753  0.338870  0.081595  0.471474  0.267443  0.453351   
2  0.584542  0.032594  0

### 9. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [80]:
dfs = pd.concat([pd.read_csv("" + f) for f in result])
medians=dfs[].median()

SyntaxError: invalid syntax (Temp/ipykernel_12512/731537023.py, line 2)

### 10. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [83]:
new_df=dfs.assign(newColumn = dfs.head(18))


ValueError: cannot reindex from a duplicate axis

### 11. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [76]:
df = pd.read_csv(r'C:\Users\benja\IronHack\ironhack-firstweek\tutorial_lab\lab-list-comprehensions\data', usecols=[''])

print(df.head())

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\benja\\IronHack\\ironhack-firstweek\\tutorial_lab\\lab-list-comprehensions\\data'